name: Generate CV by Ruby
on:
  workflow_call:
    inputs:
      file_full_path:
        required: true
        type: string
      language:
        required: true
        type: string
      skip:
        required: false
        default: false
        type: boolean

jobs:
  generate-cv-by-ruby:
    name: CV (Ruby) in ${{ inputs.language }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ !inputs.skip }}
        uses: actions/checkout@v4

      - name: Configure ruby
        if: ${{ !inputs.skip }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Generate ${{ inputs.language }} CV
        if: ${{ !inputs.skip }}
        run: bundle exec ruby ruby/scripts/generate_cv.rb --path=${{ inputs.file_full_path }}

      - name: Upload artifact
        if: ${{ !inputs.skip }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.language }} CV
          path: exported/*.pdf
          if-no-files-found: 'error'
          retention-days: 5