name: PR validations

on:
  pull_request:
    branches:
      - develop
    types:
      - synchronize
      - opened
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  changes:
    # This approach ensures the workflow is executed and skip the checks in cases they are not needed.
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      assets: ${{ steps.changes.outputs.assets }}
      ruby: ${{ steps.changes.outputs.ruby }}
    steps:
      - name: Analyze changed files
        id: changes
        uses: dorny/paths-filter@v3
        with:
          predicate-quantifier: 'every'
          filters: |
            assets:
              - 'assets/**'
            ruby:
              - 'ruby/**'
              - '!ruby/env_setup/**'

  static-checks:
    name: Static checks
    needs: changes
    if: needs.changes.outputs.assets == 'true' || needs.changes.outputs.ruby == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Rubocop checks
        uses: reviewdog/action-rubocop@v2
        with:
          skip_install: true
          use_bundler: true
          fail_on_error: true
          filter_mode: nofilter
          only_changed: true

  generate-cv-by-ruby-english:
    name: CV (Ruby) in English
    needs:
      - changes
      - static-checks
    if: needs.changes.outputs.assets == 'true' || needs.changes.outputs.ruby == 'true'
    uses: RegFacu/CV/.github/workflows/generate-cv-by-ruby.yml@v1
    with:
      file_full_path: assets/data/english.yml
      language: English

  generate-cv-by-ruby-spanish:
    name: CV (Ruby) in Spanish
    needs:
      - changes
      - static-checks
    if: needs.changes.outputs.assets == 'true' || needs.changes.outputs.ruby == 'true'
    uses: RegFacu/CV/.github/workflows/generate-cv-by-ruby.yml@v1
    with:
      file_full_path: assets/data/spanish.json
      language: Spanish