name: PR validations

on:
  pull_request:
    branches:
      - develop
    types:
      - synchronize
      - opened
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-cv-by-ruby:
    name: CV (Ruby)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [spanish, english]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Generate ${{ matrix.language }} CV
        run: bundle exec ruby ruby/scripts/generate_cv.rb --path=assets/data/${{ matrix.language }}.json

      - name: Show summary information
        run: echo "::notice title=CV::${{ matrix.language }} CV Generated"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.language }} CV
          path: exported/cv_${{ matrix.language }}.pdf
          if-no-files-found: 'error'
          retention-days: 5