name: PR validations

on:
  pull_request:
    branches:
      - develop
    types:
      - synchronize
      - opened
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    # This approach ensures the workflow is executed and skip the checks in cases they are not needed.
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.changes.outputs.src }}
    steps:
      - name: Analyze changed files
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'assets/**'
              - 'ruby/**'

  generate-cv-by-ruby:
    name: CV (Ruby) in ${{ matrix.language }}
    needs: changes
    if: needs.changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - file: spanish.json
            language: Spanish
          - file: english.yml
            language: English
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Generate ${{ matrix.language }} CV
        run: bundle exec ruby ruby/scripts/generate_cv.rb --path=assets/data/${{ matrix.file }}

      - name: Show summary information
        run: |
          echo "::notice title=${{ matrix.language }} CV::CV Generated"
          echo "${{ matrix.language }} CV Generated" >> $GITHUB_STEP_SUMMARY

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.language }} CV
          path: exported/*.pdf
          if-no-files-found: 'error'
          retention-days: 5